# Node Information
data-path="/opt/besu/data"
genesis-file="/opt/besu/config/genesis.json"
logging="INFO"
bootnodes=["enode://5f029214fb04a85f9baa769ff86222d6c38966af83b5adea1924e98baf633aa927a48b885d4e817264fc8ec59711f89ea67c270cbd9b6b67d84ebb1dee5718b2@172.16.240.30:30303"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN"]
host-allowlist=["*"]
rpc-http-cors-origins=["all"]
p2p-host="0.0.0.0"
